workflows:
  ios-ipa-upload:
    name: SCInsta IPA Upload to TestFlight
    max_build_duration: 60
    environment:
      vars:
        APP_STORE_CONNECT_ISSUER_ID: 22cf2e9e-300f-4fcf-9e67-f5a8f5ad056b # From your YAML
        APP_STORE_CONNECT_KEY_IDENTIFIER: Z963JRMC83 # From your YAML
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(Z0FBQUFBQmhnYmZoNzBjTFAtNTM0LWI0dGF6dTM2ZmdmSTA5UnpCTXBFeXNKYzNCZmRxM0xZT3cxa3I5bnRrcTZKSjUwZU5JSGtBNk1ZUkY4aDB3NWlGejk2UzFaNER4anQ0bmVEcmJqWlR2SnlWWVB5ZUx4TlYzck1TazJPaWY4alVSSktvUnV5S21UcllnZEhXN1h2ejZJUTYwLW1SWGp4TURiMUpvVGhYT1Zoei1zQi02NTAxVzlaMTJpOUhLblFuUVptMHgxOXJHLU1RLVV3dktJc0x1ZndpcVhIRnhPR01MZXdVOXFfV0t6eTRzaFN2cWNPazNqOVNDcXU5TGVZQmIwVUV0QmhJQ2hPSjRJNXhUcWo4MDRvd2RZZkxuOWpiZnJEcl9lM2FmMHNnanFqYjE2ZmdHWWxDY3ZKelFXVklBQ0hHOTRNaHRXTWplbmpfZXhVN25fZTVCRTZYdnpoQ0FWRGg5OUs5MVM3WDlEVFE2WUVMQUJBbThLRGNTN3Q0TGJMZmE3c2JuVjA0NjdUaWJjQjcwakJTeXdabWlyX3Eya1YyQWJqMFA2X3JveHdpTzNNTT0=) # From your YAML
        BUNDLE_ID: com.burbn.instagram # Instagram’s bundle ID
        SCINSTA_IPA_URL: "https://your-storage-service.com/SCInsta.ipa" # Update with SoCuul’s IPA URL
      xcode: 16.1 # Match your previous setup
    scripts:
      - name: Download Pre-Built IPA
        script: |
          echo "Downloading SCInsta IPA..."
          curl -L -o SCInsta.ipa "$SCINSTA_IPA_URL" || {
            echo "Failed to download IPA from $SCINSTA_IPA_URL"
            exit 1
          }
      - name: Set up keychain
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --create
      - name: Use system default keychain
        script: |
          keychain add-certificates
      - name: Re-Sign IPA
        script: |
          echo "Re-signing IPA..."
          mkdir -p signed
          # Unzip IPA
          unzip SCInsta.ipa -d Payload
          # Copy provisioning profile (fetched by fetch-signing-files)
          cp "$HOME/Library/MobileDevice/Provisioning Profiles"/*.mobileprovision Payload/Payload/com.burbn.instagram.app/embedded.mobileprovision
          # Sign with codesign
          /usr/bin/codesign -f -s "iPhone Distribution" Payload/Payload/com.burbn.instagram.app || {
            echo "Code signing failed."
            exit 1
          }
          # Re-zip IPA
          cd Payload
          zip -r ../signed/SCInsta.ipa . || {
            echo "Failed to zip IPA."
            exit 1
          }
      - name: Verify IPA
        script: |
          if [ -f "signed/SCInsta.ipa" ]; then
            echo "IPA ready for TestFlight: signed/SCInsta.ipa"
          else
            echo "IPA not found!"
            exit 1
          fi
    artifacts:
      - signed/SCInsta.ipa
    publishing:
      app_store_connect:
        api_key: Encrypted(Z0FBQUFBQmhnYmZoNzBjTFAtNTM0LWI0dGF6dTM2ZmdmSTA5UnpCTXBFeXNKYzNCZmRxM0xZT3cxa3I5bnRrcTZKSjUwZU5JSGtBNk1ZUkY4aDB3NWlGejk2UzFaNER4anQ0bmVEcmJqWlR2SnlWWVB5ZUx4TlYzck1TazJPaWY4alVSSktvUnV5S21UcllnZEhXN1h2ejZJUTYwLW1SWGp4TURiMUpvVGhYT1Zoei1zQi02NTAxVzlaMTJpOUhLblFuUVptMHgxOXJHLU1RLVV3dktJc0x1ZndpcVhIRnhPR01MZXdVOXFfV0t6eTRzaFN2cWNPazNqOVNDcXU5TGVZQmIwVUV0QmhJQ2hPSjRJNXhUcWo4MDRvd2RZZkxuOWpiZnJEcl9lM2FmMHNnanFqYjE2ZmdHWWxDY3ZKelFXVklBQ0hHOTRNaHRXTWplbmpfZXhVN25fZTVCRTZYdnpoQ0FWRGg5OUs5MVM3WDlEVFE2WUVMQUJBbThLRGNTN3Q0TGJMZmE3c2JuVjA0NjdUaWJjQjcwakJTeXdabWlyX3Eya1YyQWJqMFA2X3JveHdpTzNNTT0=)
        key_id: Z963JRMC83
        issuer_id: 22cf2e9e-300f-4fcf-9e67-f5a8f5ad056b
        submit_to_testflight: true
        beta_groups:
          - Internal Testers # Update with your TestFlight group name